export const images = [
  "/images/card1.jpg",
  "/images/card2.jpg",
  "/images/card3.jpg",
  "/images/card4.jpg",
  "/images/card5.jpg",
  "/images/card6.jpg",
  "/images/card7.jpg",
  "/images/card8.jpg",
  "/images/card9.jpg",
  "/images/card10.jpg",
  "/images/card11.jpg",
  "/images/card12.jpg",
  "/images/card13.jpg",
  "/images/card14.jpg",
  "/images/card15.jpg",
  "/images/card16.jpg",
  "/images/card17.jpg",
  "/images/card18.jpg",
  "/images/card19.jpg",
  "/images/card20.jpg",
  "/images/card21.jpg",
  "/images/card22.jpg",
  "/images/card23.jpg",
  "/images/card24.jpg",
  "/images/card25.jpg",

];